### PR TITLE
Automatic testing suite and DB state fetching/updating

### PR DESCRIPTION
**Pull request by olsonadr**
Relevant changes include:
- added a dedicated workflow that runs local end-to-end tests for the api and lambda on all pushes as well as on PRs to main
- added this testing step to the deployment workflow
- renamed the workflows to be more descriptive
- added the ```state_update.py``` script that updates the ```state.csv``` to have longformer embeddings from the current state of the database
- added this state_update.py updating to the deployment and testing workflows
- updated the README to include these new and changed details
- adopted relative imports for intra-project helper function usage
- added new required environment variable of a mongodb connection string to the README

This may end up with slight conflicts with your README changes once your pr is finished @smcgregor

### CODE REVIEW

**Comment by smcgregor** [comment]
I have a few questions on this, but I think it would be best for me to step through a complete run with the secrets in place before returning to the code level. I am going to merge, then I will update my README PR from `main`.

**Comment by smcgregor** [comment]
I see you opened the pull request from your main branch. In general, it is best to consider a specific branch of a specific fork to be the sole "main." Since this repository is that upstream fork, you should do all of your development on branches that are not `main` and open pull requests against this repo's main. This will solve a lot of problems you will experience in the future.

Please note that when I merge this, I am going to squash all the commits, which will mean your main and this one will be out of sync. I recommend in this instance that you rename your main branch to something else, then create a new main from this repo's current state. From that point forward you should create every feature branch from the definitive main and never touch it except to update it to match this fork.

**Comment by olsonadr** [comment]
I think that all makes sense. The main reason we've maintained a "main" branch on our fork was to test deployment work. Would it be a bad idea to rename our "main" to "staging" or "dev-deploy" or something similar so we can still make sure deployment will work before we make PRs to you?

If so we could create a second "staging" environment on the repo and rename "aws_secrets" to "production" to fit that scheme. 

Last, if we were to have a test deployment staging branch on our repo, would it be best to do our PRs from their to your main, or still from the individual feature branches?

I guess an alternative could be directly, manually deploying from our feature branches to some staging environment to test that, rather than maintaining a branch for that use.

**Comment by smcgregor** [comment]
Ah, got it. Let me finish onboarding and then let's talk about this. Note: I tried to open a pull request against your `main` to fix a typo and it would not let me create a branch, but it _did_ allow me to commit directly to main. So you have a new commit on your main. (sorry, for the drive by changeset)

**Comment by smcgregor** [comment]
I put the secrets in place, merging this now. Let's see what happens!

**Pull request merged**
